

server.port=${PORT:8080}


# ---- MySQL ----
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ---- JWT ----
app.jwt.secret=FlowerShopSuperSecretKey2024MustBe256BitsLong!!
app.jwt.expiration-ms=86400000


# ---- Admin credentials (for first-time seed) ----
app.admin.email=bcfreshnfresh@gmail.com
app.admin.password=Meteor123$

shop.name=Pooja Flowers Hyderabad
shop.location.lat=17.525450
shop.location.lon=78.368997
shop.delivery.max-km=12



# ---- File Upload ----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/products
spring.web.resources.static-locations=classpath:/static/,file:./


spring.mail.username=bcfreshnfresh@gmail.com

brevo.api.key=${BREVO_API_KEY}

app.admin.email=bcfreshnfresh@gmail.com
app.name=BC Fresh n Fresh
app.cors.allowed-origins=https://bcfreshnfresh.netlify.app



cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


